branches:
  only:
  - master
  - "/^v.*$/"
language: cpp
matrix:
  include:
  - name: Linux x86_64
    dist: bionic
    script:
    - make -j 4 PTR_SIZE="-m64" WANT_JIT=1 HAVE_COMPOSITION=1
    - zip lutro-Linux-x86_64.zip lutro_libretro.so
  - name: OSX x86_64
    os: osx
    osx_image: xcode11.2
    script:
    - make -j 4 PTR_SIZE="-m64" WANT_JIT=1 HAVE_COMPOSITION=1 MACOSX_DEPLOYMENT_TARGET=10.14
    - zip lutro-OSX-x86_64.zip lutro_libretro.dylib
  - name: Windows x86_64
    os: windows
    before_install:
    - choco install make --ignore-checksums
    script:
    - make platform=win -j 4 PTR_SIZE="-m64" WANT_JIT=1 HAVE_COMPOSITION=1
    - 7z a lutro-Windows-x86_64.zip lutro_libretro.dll
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: edJx64MPdQpu/TTbtImLqTJi4AKHv+b23rsump19OB5qhmxVqCisrxb99dVRT4tiBvp8rhMHWpUOrzoeixXzHZhpF8UC71aPZe/dYQZQ15vzjqThHVQPEslTPJ+ENnyHHjZEkCkstQdX6G6ElV46nxgb4nCl9HiFf+HlL8REbjC5FcLBVzO8iEKb9F8WuBovokr9tTkg2ZEOOeGirf653hJVFHifnWf+u9HPZs93fTAg8LUVHkMphaNA0jNpc2U8EpQduqKwxdxbTVj5qDFGTaIdeR4pvZJVH8x725fxUG+0HWqH98J40enPL4CdjwRRLvS53KVGQXZnvoAtrrgwIY9N3Ugpg6KXrT6c/SgOA94aWnmal3K7b2rHJ13BFOvd9sz4dA/SKnpx+mGZV9eH8nwNpujrBEV/3cClDkTznakkteK6qVe1DruTRlAQqpSmkqwtLZp/BsygjsJ9rUMHImt794i0wn8eZdR/yjeHXLsZkEyxqbltVm1AKYWdGYMrfrID6OpVtO2eSkI0d7GtvJXAAJ3UcI8dg/JQUfjVQPM5JGo0G+ZEksMnj7hgiBnm2rwL1viBNn88c2ugFi3UlxwcCm/VQ1TQ2rqtsdsDM9pj0euWMAtzqTFps5xF6iigYyLZx8X68Mxo+ojrwT99j/boz84QViCrNDB8YxaQ8qM=
  file:
  - lutro-Linux-x86_64.zip
  - lutro-Linux-arm64.zip
  - lutro-Linux-arm.zip
  - lutro-OSX-x86_64.zip
  - lutro-Windows-x86_64.zip
  on:
    repo: piepacker/lutro
    tags: true
